spring:
  profiles:
    active: dev
knife4j:
  enable: true
  documents:
    -
      group: 1.X版本
      name: 自定义文档
      locations: classpath:markdown/*
    -
      group: 1.X版本
      name: 接口签名
      locations: classpath:sign/*
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: true
    enableRequestCache: false
    enableHost: false
    enableHostText: 192.168.0.193:8000
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/home.md
    enableSearch: true
    enableFooter: true
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2019-[天津联物科技有限公司](www.lianwukeji.com)
    enableDynamicParameter: false
    enableDebug: true
    enableOpenApi: true
    enableGroup: true
  cors: false
  production: false
  basic:
    enable: true
    username: test
    password: 12313
